# Generated by Django 3.0 on 2019-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
