# Generated by Django 3.0 on 2019-12-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_view', '0002_auto_20191210_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
